version: '3'
services:
    lab_1:
        build:
            context: .
            dockerfile: ./server.dockerfile
        command: tail -f /dev/null
        networks:
            lab_net:
                ipv4_address: 172.28.0.10
    lab_2:
        build:
            context: .
            dockerfile: ./server.dockerfile
        command: tail -f /dev/null
        networks:
            lab_net:
                ipv4_address: 172.28.0.11
networks:
    lab_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/24