version: '3'
services:
    web:
        build:
            context: .
            dockerfile: ../sources/dockerfile/web.dockerfile
        ports:
            - 80:80
            - 443:443
        networks:
            lab_net:
                ipv4_address: 172.28.0.11
networks:
    lab_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/24
