version: '3'
services:
    rebond:
        build:
            context: .
            dockerfile: ./Dockerfile
        networks:
            lab_net:
                ipv4_address: 172.28.0.10
networks:
    lab_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/24
